WEB_OPENTAG_H1 = "<h1>"
WEB_ENDTAG_H1 = "</h1>"
WEB_OPENTAG_H2 = "<h2>"
WEB_ENDTAG_H2 = "</h2>"
WEB_OPENTAG_H3 = "<h3>"
WEB_ENDTAG_H3 = "</h3>"
WEB_OPENTAG_H4 = "<h4>"
WEB_ENDTAG_H4 = "</h4>"
WEB_OPENTAG_H5 = "<h5>"
WEB_ENDTAG_H5 = "</h5>"
WEB_OPENTAG_H6 = "<h6>"
WEB_ENDTAG_H6 = "</h6>"

WEB_OPENTAG_HEADING_LIST = [
    WEB_OPENTAG_H1,
    WEB_OPENTAG_H2,
    WEB_OPENTAG_H3,
    WEB_OPENTAG_H4,
    WEB_OPENTAG_H5,
    WEB_OPENTAG_H6,
]
WEB_ENDTAG_HEADING_LIST = [
    WEB_ENDTAG_H1,
    WEB_ENDTAG_H2,
    WEB_ENDTAG_H3,
    WEB_ENDTAG_H4,
    WEB_ENDTAG_H5,
    WEB_ENDTAG_H6,
]
